### PR TITLE
Youtube clone project: side-bar

### PR DESCRIPTION
**Pull request by ghost**
We did the following:

-Added the menu bar.
-Added the side-bar.
-Added the video section.
-Ran validations on our Html and CSS.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi team, good job:+1:. Just a few changes:**

1. Use semantic html - nav, main and footer in your html

**Optional change:** I couldn't play the video. We can embed a youtube video instead.

_**Make these changes and submit another code review request**_

**Cheers:stars:**

**Comment by ghost** [comment]
-Added the nav, footer and main semantic Html.
-Embed the youtube video

**Comment by majovanilla** [comment]
Hey @evabanegacom and @blackpintz , 👋

## You did an *amazing*🌟 ✨ job working on this project! 👊🏻  💯
I really liked the final look of your clone. 

However, there is still one error on your HTML that needs to be corrected.
Screenshot from 2020-02-21 03-33-01


**CHANGES REQUIRED**

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Check your live version link, because it's broken
- Be careful when you merge, cause this branch has no Readme file.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by ghost** [comment]
-Removed the frameborder attribute and fixed the live demo link.

About the merge, we are anticipating a merge conflict and have identified a way to fix that.

**Comment by SofiBretz** [comment]
### Well done!!!  👏

**Good work! Project Approved✨.**

You can merge 👍

SofiBretz.

**Pull request merged**
